# Generated by Django 3.2.15 on 2022-09-02 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20220902_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='zzzz@yyy', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Japan', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default='ADCD', max_length=50),
        ),
    ]
