# Generated by Django 3.2.15 on 2022-09-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20220903_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_address', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=4)),
                ('send_receive_address', models.CharField(max_length=30)),
                ('t_status', models.CharField(max_length=5)),
                ('t_history', models.TextField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.user')),
            ],
        ),
    ]
