# Generated by Django 3.2.15 on 2022-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_nft'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=4)),
                ('send_receive_address', models.CharField(max_length=30)),
                ('t_status', models.CharField(max_length=5)),
                ('t_history', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='nft',
            old_name='t_history',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='send_receive_address',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='t_status',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='transaction_type',
        ),
    ]
