# Generated by Django 3.2.15 on 2022-09-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
