# Generated by Django 3.2.15 on 2022-09-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_password_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upreference',
            name='image',
        ),
    ]
