# Generated by Django 3.2.15 on 2022-09-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_upreference_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
